model:
  type: AbMEGD
  res_feat_dim: 128
  pair_feat_dim: 64
  diffusion:
    num_steps: 100
    eps_net_opt:
      num_layers: 6
      #num_layers: 2
  train_structure: true
  train_sequence: true

train:
  loss_weights:
    rot: 1.0
    pos: 1.0
    seq: 1.0
  max_iters: 400_000
  #max_iters: 40
  val_freq: 1000
  #val_freq: 20
  batch_size: 8
  seed: 2024
  max_grad_norm: 100.0
  optimizer:
    type: adam
    lr: 1.e-4
    weight_decay: 0.0
    beta1: 0.9
    beta2: 0.999
  scheduler:
    type: plateau
    factor: 0.8
    patience: 10
    min_lr: 5.e-6

dataset:
  train:
    type: sabdab
    summary_path: ./data2024/sabdab_summary_all.tsv
    chothia_dir: ./data2024/all_structures/chothia
    processed_dir: ./data2024/processed
    split: train
    transform:
      - type: mask_single_cdr
      - type: merge_chains
      - type: patch_around_anchor
  val:
    type: sabdab
    summary_path: ./data2024/sabdab_summary_all.tsv
    chothia_dir: ./data2024/all_structures/chothia
    processed_dir: ./data2024/processed
    split: val
    transform:
      - type: mask_single_cdr
        selection: CDR3
      - type: merge_chains
      - type: patch_around_anchor
